### Login
POST https://reqres.in/api/login
Content-Type: application/json

{
    "email": "eve.holt@reqres.in",
    "password": "cityslicka"
}

### Register
POST https://reqres.in/api/register
Content-Type: application/json

{
    "email": "eve.holt@reqres.in",
    "password": "cityslicka"
}

